services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      TZ: Europe/Paris
    volumes:
      - ./.data:/var/lib/mysql
    ports:
      - 3306:3306
