version: "3.8"
services:
  traefik:
    image: "traefik:2.5.6"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  php-apache:
    build:
        context: ../php-dockerfile
#SELECT HERE YOUR PHP VERSION FOR YOUR ENVIRONMENT
        dockerfile : php-8.2.Dockerfile
#        dockerfile : php-7.4.Dockerfile

    depends_on:
      - "traefik"
      - "mysql"
    volumes:
  # SELECT HERE THE CORE VERSION OF DOLIBARR
      - "../dolibarr-core/dolibarr-develop:/var/www/html/dolibarr"
      - "../custom:/var/www/html/dolibarr/htdocs/custom"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`dlb2003.localhost`, `localhost`, `lvh.me`, `pmamp.lvh.me`, `127.0.0.1`)"
      - "traefik.http.routers.php-apache.entrypoints=web"

  mysql:
  # SELECT HERE THE VERSION OF MYSQL (or something else)
    image: "mariadb:latest"
    #image: "mysql:8.0.27"
    # Uncomment line below if you are using a Mac with the M1 chip
    #platform: linux/amd64
    depends_on:
      - "traefik"
    volumes:
      #- "./mysql_seed.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
      - "./dbdata:/var/lib/mysql"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: "rootPASS"
      MYSQL_DATABASE: "dolibarr"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "dbpass"
    labels:
      - "traefik.enable=false"

  phpmyadmin:
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - "mysql"
    links:
      - "mysql"
    environment:
      PMA_HOST: "mysql"
      PMA_PORT: "3306"
      UPLOAD_LIMIT: "256M"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pma.localhost`, `pma.lvh.me`)"
      - "traefik.http.routers.whoami.entrypoints=web"

networks:
  default:
    name: "traefikNetwork"
