services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      TZ: Europe/Paris
    volumes:
      - ./.db:/var/lib/mysql

networks:
  default:
    name: mariadb_network
