services:
  traefik:
    container_name: traefik
    image: traefik:v3
    ports:
      - 80:80
      # - 443:443
      - 8080:8080
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-ssl-certs:/ssl-certs
      # - ./logs:/var/log

volumes:
  traefik-ssl-certs:
    driver: local
