services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
    ports:
      - 9090:80
    networks:
      - mariadb_network

networks:
  mariadb_network:
    external: true
