services:
  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_PLUGINS: 'dark-switcher codemirror tables-filter'
      # ADMINER_DESIGN: '' # For known design
    ports:
      - 9080:8080
    networks:
      - db_default

networks:
  db_default:
    external: true
