services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      TZ: Europe/Paris
    volumes:
      - ./.mariadb:/var/lib/mysql
